apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-scheduler
  namespace: kube-system
---
# 1. PYTHON 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-scheduler-extender
  template:
    metadata:
      labels:
        app: energy-scheduler-extender
    spec:
      containers:
        - name: extender
          image: localhost:5000/energy-scheduler:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: energy-scheduler-extender
  namespace: kube-system
spec:
  selector:
    app: energy-scheduler-extender
  ports:
    - port: 80
      targetPort: 8888
---
# 2. THE CUSTOM SCHEDULER CONFIGURATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: energy-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: energy-aware-scheduler
    extenders:
      - urlPrefix: "http://energy-scheduler-extender.kube-system.svc.cluster.local:80"
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 1
        enableHTTPS: false
        nodeCacheCapable: false
---
# 3. THE SECONDARY SCHEDULER POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-aware-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: energy-aware-scheduler
  template:
    metadata:
      labels:
        component: energy-aware-scheduler
    spec:
      serviceAccountName: energy-scheduler
      containers:
        - name: kube-scheduler
          image: registry.k8s.io/kube-scheduler:v1.30.0  # Adjust version to match your cluster (kubectl version)
          command:
            - kube-scheduler
            - --config=/etc/kubernetes/energy-scheduler/config.yaml
            - --leader-elect=false
            - --scheduler-name=energy-aware-scheduler
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes/energy-scheduler
      volumes:
        - name: config-volume
          configMap:
            name: energy-scheduler-config
