apiVersion: v1
kind: Pod
metadata:
  # name: test-green-pod
  name: test-srsran-pod
  namespace: default
spec:
  schedulerName: GreenScheduler # This routes the pod to your custom binary
  containers:
  - name: test-container
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
